//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PessoaCore.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbPessoaEntities : DbContext
    {
        public DbPessoaEntities()
            : base("name=DbPessoaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_cidade> tbl_cidade { get; set; }
        public virtual DbSet<tbl_estado> tbl_estado { get; set; }
        public virtual DbSet<tbl_pessoa> tbl_pessoa { get; set; }
        public virtual DbSet<tbl_pessoa_contato> tbl_pessoa_contato { get; set; }
        public virtual DbSet<tbl_pessoa_endereco> tbl_pessoa_endereco { get; set; }
        public virtual DbSet<tbl_pessoa_fisica> tbl_pessoa_fisica { get; set; }
        public virtual DbSet<tbl_pessoa_juridica> tbl_pessoa_juridica { get; set; }
    }
}
