//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PessoaCore.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_pessoa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_pessoa()
        {
            this.tbl_pessoa_contato = new HashSet<tbl_pessoa_contato>();
            this.tbl_pessoa_endereco = new HashSet<tbl_pessoa_endereco>();
        }
    
        public int cod_pessoa { get; set; }
        public string txt_pessoa { get; set; }
        public string txt_email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_pessoa_contato> tbl_pessoa_contato { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_pessoa_endereco> tbl_pessoa_endereco { get; set; }
        public virtual tbl_pessoa_fisica tbl_pessoa_fisica { get; set; }
        public virtual tbl_pessoa_juridica tbl_pessoa_juridica { get; set; }
    }
}
