//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PessoaCore.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_estado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_estado()
        {
            this.tbl_cidade = new HashSet<tbl_cidade>();
            this.tbl_pessoa_endereco = new HashSet<tbl_pessoa_endereco>();
        }
    
        public int cod_estado { get; set; }
        public string txt_estado { get; set; }
        public string txt_sigla { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_cidade> tbl_cidade { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_pessoa_endereco> tbl_pessoa_endereco { get; set; }
    }
}
